rebber-plugins/math: fix some escaping issues
zestedesavoir/zmarkdown pull request #478
Opened 2022-11-15 19:28 UTC by artragis

fix #477

2022-11-29 20:45 UTC, StaloneLab reviewed
Hi, thanks for the proposed fix, and the added unit test. Unfortunately, I don't think your solution will work for every possible command: for instance, consider `\%`, which is in the list of allowed commands. This command does match your RegEx (the `%` character will pass `[^\w_-]`): a command can contain non-alphanumeric characters. More generally, finding a solution in the form of a negative search does not seem that easy to me because the command `\{` is in the allowed list. If you have an idea on how to fix, then I would be happy to review again, otherwise the test will be merged anyway.

2022-11-30 20:57 UTC, artragis commented
Let me see that next week. 

I have an idea but no time to implement it now.

2022-12-12 20:43 UTC, StaloneLab commented
Hi, have you had some time to work on the problem? I am planning to work on it next week if you have no time, so keep me informed 😉 .

2022-12-12 20:55 UTC, artragis commented
I think I can do it by the end of the week. If I can't I will keep you informed on thursday

2022-12-13 20:17 UTC, artragis commented
Now, I have a better algorithm that passes the tests.

I also added the `\%` command.

2022-12-13 20:42 UTC, artragis commented
sorry for all the mess, I did not expect the global test suite to have more tests that were not expecting the right result.

2022-12-14 16:58 UTC, StaloneLab requested changes
Some examples do not work as expected I think. For instance consider the two following cases (one example per line):

```latex
a=\mathrm{b}\\\outputrce{\inputrce{/bin/bash} hello hello}
\\cdleft{\frac{1}{2}}
```

While reviewing your work, I got the idea to eat *at most* two slashes at the beginning of the command, so I am issuing a commit on your PR (if I can) to show a solution I have in mind, but as you have worked on it, I would be happy to have your opinion on the changes. If you think everything is fine I will arrange merging.

2022-12-14 16:58 UTC, StaloneLab commented on packages/rebber-plugins/dist/preprocessors/mathEscape.js
> +  return endOfCommandChars.indexOf(currentChar) !== -1;
Use `includes` instead of `indexOf` if not using the index.

2022-12-14 17:51 UTC, artragis commented
If you have a PR you can send it, I will certainly review it and merge it if it works.

2022-12-14 21:46 UTC, artragis commented
Everything seems to be good on my side.

2022-12-15 09:47 UTC, StaloneLab commented
I just merged the changes by squashing your commits. Thanks for the help!

2022-12-15 09:47 UTC, closed without merging