Fix/482 843
zestedesavoir/zmarkdown pull request #484
Opened 2022-12-19 20:53 UTC by artragis

Fix and add test for those two cases

2022-12-21 10:36 UTC, StaloneLab requested changes
Fine by me, only two requested changes:

- could you remove your additions in `katexConstants.json`, it should still work (see comment);
- could you compile your changes, using `npm run build -- --scope=rebber-plugins`.

2022-12-21 10:36 UTC, StaloneLab commented on packages/rebber-plugins/src/preprocessors/katexConstants.json
> +["\\acute","\\grave","\\ddot","\\tilde","\\bar","\\breve","\\check","\\hat","\\vec","\\dot","\\mathring","\\widecheck","\\widehat","\\widetilde","\\overrightarrow","\\overleftarrow","\\Overrightarrow
All the commands you added already exist in the file (check before with a quick search), some of them even appear twice. I will regenerate the constants file before releasing to remove the duplicates, but can you remove yours already?

The only exception (symbol not already in the file) is the `\[` which doesn't seem to be parsed by KaTeX (from what I can see in the live demo), so no changes should be required on this file.

2022-12-21 10:36 UTC, StaloneLab commented on packages/rebber-plugins/src/preprocessors/mathEscape.js
> +const endOfCommandChars = ['\\', '[', ']', '{', '}', ' ', '(', ')', '\t', '\n', '^', '_', ',']
This array seems to just grow bigger and bigger :smile: 

If we have one more problem, I will find another way to detect end of command.

2022-12-22 18:33 UTC, artragis commented
Seems to be ok by now.

2022-12-27 09:31 UTC, StaloneLab approved these changes
Fine by me, I think it will be released as a bugfix version, see the other PR.

2022-12-27 09:31 UTC, merged